### ISSUE TITLE
Deploying Issue

### ISSUE THREAD

**Issue by fthamura** [javaee-samples/docker-java#103]
I use the simple-sample project, and follow this instruction

https://github.com/javaee-samples/docker-java/blob/master/readme.html#_build_and_deploy_java_ee_7_application

I did clone under my folder /home/mervo

so the code will be under /home/mervo/javaee7-simple-sample

I tought the .war is in the /target rather /deployments

I use Linux.

docker run --name wildfly -d -p 8080:8080 -v /home/mervo/javaee7-simple-sample/target:/opt/jboss/wildfly/standalone/deployments/:rw jboss/wildfly

**Comment by arun-gupta** [comment]
Instructions updated.
