### ISSUE TITLE
Not able to download boot2docker

### ISSUE THREAD

**Issue by Schreuderjg** [javaee-samples/docker-java#105]
Hi, i'm not able to download boot2docker, while trying to create a virtual-machine.

Getting the following error:

/usr/local/bin$ sudo docker-machine create --driver=virtualbox lab
No default boot2docker iso found locally, downloading the latest release...
Error creating machine: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: i/o timeout
You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by delgurth** [comment]
Just go to https://github.com/boot2docker/boot2docker/releases and click on the boot2docker.iso (v1.9.0)

After that move that .iso to the docker cache directory (~/.docker/machine/cache on mac / linux /Users/yourUsername/.docker/machine/cache on windows)

**Comment by Schreuderjg** [comment]
thx will try that.

**Comment by arun-gupta** [comment]
Merged and integrated!
