### ISSUE TITLE
"You may be getting rate limited by Github" for Swarm

### ISSUE THREAD

**Issue by WanderW** [javaee-samples/docker-java#110]
root@wander-laptop:~/nljug/docker_swarm# !dock
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://af987d7946f6782bc381c30b9fd5720d swarm-master
Creating CA: /home/wander/.docker/machine/certs/ca.pem
Creating client certificate: /home/wander/.docker/machine/certs/cert.pem
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Error demarshaling the Github API response: json: cannot unmarshal object into Go value of type []struct { TagName string "json:\"tag_name\"" }
You may be getting rate limited by Github.
root@wander-laptop:~/nljug/docker_swarm# docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://af987d7946f6782bc381c30b9fd5720d swarm-master
Host already exists: "swarm-master"

**Comment by arun-gupta** [comment]
This needs to be updated based upon https://github.com/docker/machine/pull/1940.

**Comment by arun-gupta** [comment]
This error should not occur if the proposed workaround is used.
