### ISSUE TITLE
KUBERNETES_DEFAULT_PROVIDER required for VirtualBox on Windows

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/docker-java#126]
On Windows, if VirtualBox is not included in the PATH, then Kubernetes cluster does not start up.

It requires to set PATH to include VirtualBox directory. Make sure to check `vboxmanage` can be invoked from the command line.

**Comment by suepan** [comment]
```
$ ./cluster/kube-up.sh
Starting cluster using provider: vagrant
... calling verify-prereqs
Can't find the necessary components for the virtualbox vagrant provider, please fix and retry.
```

**Comment by arun-gupta** [comment]
The relevant section that needs to be included is from https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md#setup:

If you installed more than one Vagrant provider, Kubernetes will usually pick the appropriate one. However, you can override which one Kubernetes will use by setting the VAGRANT_DEFAULT_PROVIDER environment variable:

export VAGRANT_DEFAULT_PROVIDER=parallels
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh

**Comment by arun-gupta** [comment]
Updated the instructions
