### ISSUE TITLE
./cluster/kubectl.sh get se no longer works in kubernetes 1.1.2

### ISSUE THREAD

**Issue by jayallard** [javaee-samples/docker-java#128]
kubectl.sh

"get se" no longer works
"get svc" works
"get service" also works

**Comment by arun-gupta** [comment]
`get se` seems to work with 1.1.2:

```
kubernetes > ./cluster/kubectl.sh get se
NAME         LABELS                                    SELECTOR   IP(S)        PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>     10.247.0.1   443/TCP
kubernetes > ./cluster/kubectl.sh get svc
NAME         LABELS                                    SELECTOR   IP(S)        PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>     10.247.0.1   443/TCP
```

Can you please paste the exact error message?

**Comment by jayallard** [comment]
Here... 

    $ ./cluster/kubectl.sh get se
    error: in version and kind for resource, no resource "se" has been defined

    $ ./cluster/kubectl.sh get svc
    NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
    kubernetes   10.247.0.1   <none>        443/TCP   <none>     1d

    $ ./cluster/kubectl.sh version
    Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2",    GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2",     GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}'

I see that even the data returned is different.
Yours: name, labels, selector, ips, ports
Mine: name, cluster_ip, external_ip, ports, selector, age

Is my context incorrect? Am I pointing to the wrong thing?

**Comment by arun-gupta** [comment]
Instructions are updated to Kubernetes 1.1.2.
