### ISSUE TITLE
Docker Compose File docker-compose-pull-images.yml for pulling images does not work

### ISSUE THREAD

**Issue by skiransp** [javaee-samples/docker-java#132]
The docker compose file docker-compose-pull-images.yml for pulling images does not work. It results in the following error.

SFOC1MQ32XHG944:attendees sid150$ docker-compose pull -f docker-compose-pull-images.yml 
Pulls images for services.

Usage: pull [options] [SERVICE...]

Options:
    --ignore-pull-failures  Pull what it can and ignores images with pull failures.
    --allow-insecure-ssl    Deprecated - no effect.

**Comment by mmagdiahmed** [comment]
the command as given in the documentation is wrong. It should be " docker-compose -f docker-compose-pull-images.yml pull"

**Comment by arun-gupta** [comment]
Already fixed by https://github.com/javaee-samples/docker-java/pull/134
