### ISSUE TITLE
Docker hands on workshop link is broken

### ISSUE THREAD

**Issue by jefly** [javaee-samples/docker-java#152]
Hi @arun-gupta I'm watching your "Refactor your Java EE application using Microservices and Containers" at safaribooksonline. You encourage us to check this link (https://htmlpreview.github.io/?https://github.com/javaee-samples/docker-java/blog/master/readme.html) but it is not working. At the end of the video you say if something is not working, send an issue. So I'm raising this issue. Please be kind enough to make the link available. Please refer below screenshot for more info.

![docker](https://cloud.githubusercontent.com/assets/1148043/21319519/8fbc85e2-c633-11e6-8a85-c4dd8843d834.png)
![docker2](https://cloud.githubusercontent.com/assets/1148043/21320004/7f5926d6-c635-11e6-905c-536bb20debb4.png)

**Comment by arun-gupta** [comment]
Updated workshop is at https://github.com/docker/labs/tree/master/developer-tools/java. This is also mentioned at https://github.com/javaee-samples/docker-java.

**Comment by jefly** [comment]
@arun-gupta I saw that link Arun but it doesn't include the full content that you showed in that video. Please Arun can you send me a pdf copy of that original full resource even, it would be a great help!!!

**Comment by arun-gupta** [comment]
@jefly That content (including slides) is now refactored into multiple repos:

https://github.com/docker/labs/tree/master/developer-tools/java
https://github.com/arun-gupta/kubernetes-java-sample/
https://github.com/arun-gupta/microservices

**Comment by jefly** [comment]
@arun-gupta thanks alot arun.
