### ISSUE TITLE
Testing Ticket Monster with Arquillian Cube

### ISSUE THREAD

**Issue by myfear** [javaee-samples/docker-java#20]
As discussed: https://github.com/arun-gupta/docker-java#test-java-ee-applications-on-docker

**Comment by arun-gupta** [comment]
TiMo references are removed from the workshop for now, they are all using Java EE 7 application. Arquillian Cube is particularly explained at: https://htmlpreview.github.io/?https://github.com/javaee-samples/docker-java/blob/master/readme.html#_test_java_ee_applications_on_docker
