### ISSUE TITLE
JBoss Developer Studio link is broken

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/docker-java#44]
https://www.jboss.org/download-manager/content/origin/files/sha256/0e/0e3e78a641196d21742730f23a6e1c9aa04e0596c16349e74dbd4ea2d1109d40/jboss-devstudio-8.1.0.GA-installer-standalone.jar is a 404. This is linked from Instructor's setup docs.

**Comment by rafabene** [comment]
Fixed in https://github.com/javaee-samples/docker-java/commit/43e3463706f370cdfc1902d3182b815c1578d194
