### ISSUE TITLE
Docker Client links are broken

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/docker-java#45]
Docker Client link is broken:

https://github.com/arun-gupta/docker-java/tree/master/attendees#install-docker-client

It refers to:

http://<INSTRUCTOR_IP>:8082/`uname -s`/x86_64/docker-latest and http://<INSTRUCTOR_IP>:8082/docker-1.6.0.exe.

Windows link should be from http://<INSTRUCTOR_IP>:8082/downloads. There is no `Darwin/x86_64/docker-latest` directory.

**Comment by rafabene** [comment]
Fixed in commit https://github.com/javaee-samples/docker-java/commit/43e3463706f370cdfc1902d3182b815c1578d194
