### ISSUE TITLE
Failed to build instructor 'http-server' container

### ISSUE THREAD

**Issue by xcoulon** [javaee-samples/docker-java#52]
I'm trying to follow the instructions on https://github.com/arun-gupta/docker-java/blob/master/instructor/readme.adoc to setup a Docker machine with all the bits for the Docker/Java lab, but I hit a problem while running Compose to build and run the containers. 
While building the http-server image (using dockerfiles/lab-httpd-server/Dockerfile), the 'RUN wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2.dmg' command fails with the following error:

...
--2015-06-05 13:16:59--  https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2.dmg
Connecting to dl.bintray.com (dl.bintray.com)|5.153.24.114|:443... connected.
HTTP request sent, awaiting response... 302
Location: https://d29vzk4ow07wi7.cloudfront.net/64c9e0a5e75ac4b987257792d08f497f6877d2fc?response-content-disposition=attachment%3Bfilename%3D%22vagrant_1.7.2.dmg%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjRjOWUwYTVlNzVhYzRiOTg3MjU3NzkyZDA4ZjQ5N2Y2ODc3ZDJmYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnZhZ3JhbnRfMS43LjIuZG1nJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDMzNTEwOTM5fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=ktvAMBytW1nNqDuc6S30ROWs-XC-EPCB8ay1wDgG77VmsOuNb1tgHzZt5d30NLdGAT-vUE3vdxKDSrsy3szD1EwiakTwC3c9FpPhB-J1-PotZzALMwxGFf-hzpMjpfRYUqI2fucBKj7Eb-SkJM4QHsR1ZhsOOeusuzpJb4pCrRc2vdU7r65lKCZ4y~KDxRZvAcEm7oaSCVa~IumF1BhqbLA8nMU8NMJ3xzOfa8qEvLhjq6wc5Fmv8RBoGmZ~CfmZqEcA5NcjsL44BBojQKKBaoqLt7daJG3ku~Tz1EqKf~29LqfAR16JqHNpb7h-mA03B-9fbi726HL18duuJO9xvQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA [following]
--2015-06-05 13:16:59--  https://d29vzk4ow07wi7.cloudfront.net/64c9e0a5e75ac4b987257792d08f497f6877d2fc?response-content-disposition=attachment;filename=%22vagrant_1.7.2.dmg%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjRjOWUwYTVlNzVhYzRiOTg3MjU3NzkyZDA4ZjQ5N2Y2ODc3ZDJmYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnZhZ3JhbnRfMS43LjIuZG1nJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDMzNTEwOTM5fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=ktvAMBytW1nNqDuc6S30ROWs-XC-EPCB8ay1wDgG77VmsOuNb1tgHzZt5d30NLdGAT-vUE3vdxKDSrsy3szD1EwiakTwC3c9FpPhB-J1-PotZzALMwxGFf-hzpMjpfRYUqI2fucBKj7Eb-SkJM4QHsR1ZhsOOeusuzpJb4pCrRc2vdU7r65lKCZ4y~KDxRZvAcEm7oaSCVa~IumF1BhqbLA8nMU8NMJ3xzOfa8qEvLhjq6wc5Fmv8RBoGmZ~CfmZqEcA5NcjsL44BBojQKKBaoqLt7daJG3ku~Tz1EqKf~29LqfAR16JqHNpb7h-mA03B-9fbi726HL18duuJO9xvQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
Connecting to d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)|54.230.185.190|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-06-05 13:16:59 ERROR 403: Forbidden.

--2015-06-05 13:16:59--  https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2.dmg
Connecting to dl.bintray.com (dl.bintray.com)|5.153.24.114|:443... connected.
HTTP request sent, awaiting response... 302
Location: https://d29vzk4ow07wi7.cloudfront.net/64c9e0a5e75ac4b987257792d08f497f6877d2fc?response-content-disposition=attachment%3Bfilename%3D%22vagrant_1.7.2.dmg%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjRjOWUwYTVlNzVhYzRiOTg3MjU3NzkyZDA4ZjQ5N2Y2ODc3ZDJmYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnZhZ3JhbnRfMS43LjIuZG1nJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDMzNTEwOTM5fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=ktvAMBytW1nNqDuc6S30ROWs-XC-EPCB8ay1wDgG77VmsOuNb1tgHzZt5d30NLdGAT-vUE3vdxKDSrsy3szD1EwiakTwC3c9FpPhB-J1-PotZzALMwxGFf-hzpMjpfRYUqI2fucBKj7Eb-SkJM4QHsR1ZhsOOeusuzpJb4pCrRc2vdU7r65lKCZ4y~KDxRZvAcEm7oaSCVa~IumF1BhqbLA8nMU8NMJ3xzOfa8qEvLhjq6wc5Fmv8RBoGmZ~CfmZqEcA5NcjsL44BBojQKKBaoqLt7daJG3ku~Tz1EqKf~29LqfAR16JqHNpb7h-mA03B-9fbi726HL18duuJO9xvQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA [following]
20 redirections exceeded.

While the URL to download the Vagrant 1.7.2 package is good (I can use it in my browser), it fails with WGET. I get 20 attempts with 403 responses before WGET fails.

**Comment by rafabene** [comment]
Fixed
