### ISSUE TITLE
Try Ticket Monster with JBDS 9 nightly instead of 8.1

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/docker-java#53]
This will allow to use only a single JBDS build as opposed to two.

**Comment by rafabene** [comment]
I tried Build id: Beta2-v20150608-1909-B3341- Build date: 20150608-1909.

Only non-blocker issue: The Docker Images view shows duplicated images name.

**Comment by arun-gupta** [comment]
Cool, can you update the instructions to use JBDS 9 nightly then?

@xcoulon may know about duplicate images?

**Comment by xcoulon** [comment]
@rafabene I'm not aware of such a bug. Do you have steps to reproduce it ?

**Comment by rafabene** [comment]
You can use these steps: https://github.com/javaee-samples/docker-java/blob/master/chapters/docker-eclipse.adoc
