### ISSUE TITLE
Update docker-machine to 3.0.0-rc2

### ISSUE THREAD

**Issue by rafabene** [javaee-samples/docker-java#57]
Try the new feature: Engine option configuration (ability to configure all engine options)

**Comment by arun-gupta** [comment]
@rafabene How would it be useful for the lab?

**Comment by rafabene** [comment]
yes. It would include the EXTRA_ARGS automatically and we could skip that from the instructor's and attendees instructions.

**Comment by arun-gupta** [comment]
Nice, simplification is good.

**Comment by arun-gupta** [comment]
Can you update the attendee and instructor's instructions as well?

**Comment by arun-gupta** [comment]
I see the instructions are already using classroom.example.com:5000. This need to wait for DNS instructions to be updated?

The lab is tomorrow and I'd like to freeze up instructions.
