### ISSUE TITLE
convert.sh should generate instructor's index.html

### ISSUE THREAD

**Issue by rafabene** [javaee-samples/docker-java#63]
It should be good if the convert.sh can update the instructor's index.html (https://github.com/javaee-samples/docker-java/blob/master/instructor/dockerfiles/lab-httpd-server/index.html )

**Comment by arun-gupta** [comment]
This is now redundant as the latest instructions are available at https://htmlpreview.github.io/?https://github.com/javaee-samples/docker-java/blob/master/readme.html.
