### ISSUE TITLE
Docker Maven Plugin working in a sandbox only

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/docker-java#73]
docker-maven-plugin is working with arungupta/wildfly:8.2, but not with arungupta/wildfly:9.0, jboss/wildfly:8.2.0.Final, or jboss/wildfly.

Investigating this with @rhuss

**Comment by rhuss** [comment]
will have a look ASAP

**Comment by rhuss** [comment]
Do you have a sample pom.xml for me which exhibits this issue ?

**Comment by arun-gupta** [comment]
Trying the project https://github.com/javaee-samples/javaee7-docker-maven over a hotel Internet connection. Will keep you updated.

**Comment by arun-gupta** [comment]
No longer an issue, seems to be working fine with the sample project. Will file a new issue if it persists in docker-java setup.
