### ISSUE TITLE
Improve lab-http-server with WGET instead of ADD

### ISSUE THREAD

**Issue by rafabene** [javaee-samples/docker-java#75]
Due to https://issues.jboss.org/browse/ORG-2414 the instructor had to download JBDS and place it inside the download folder so it could be added in lab-http-server image ( https://github.com/javaee-samples/docker-java/blob/master/instructor/dockerfiles/lab-httpd-server/Dockerfile#L15 )

Now that the wget url was fixed, we should change it to get JBDS automatically inside lab-http-server via wget

**Comment by arun-gupta** [comment]
This is now redundant as images are stored as tar files as explained in https://github.com/javaee-samples/docker-java/issues/89. All other download instructions are explained in setup already.
