### ISSUE TITLE
error pulling image (latest) from arungupta/wildfly-mysql-javaee7

### ISSUE THREAD

**Issue by eheb** [javaee-samples/docker-java#81]
on centOS 7, step : docker-compose up -d
I get this error. Do you know the solution ? Best reagrds.
Message from syslogd@ix1-dv-c6-survey-01 at Aug 20 11:35:06 ...
6288e68bb15b: Error pulling image (latest) from arungupta/wildfly-mysql-javaee7, Driver devicemapper failed to create image rootfs 7d3f07f8de5fb3a20c6cb1e4447773a5741e3641c1aa093366eaa0fc690c6417: device 7d3f07f8de5fb3a20c6cb1e4Error pulling image (latest) from arungupta/wildfly-mysql-javaee7, Driver devicemapper failed to create image rootfs 7d3f07f8de5fb3a20c6cb1e4447773a5741e3641c1aa093366eaa0fc690c6417: device 7d3f07f8de5fb3a20c6cb1e4447773a5741e3641c1aa093366eaa0fc690c6417 already exists

**Comment by arun-gupta** [comment]
Seems like this might be related to: https://github.com/docker/docker/issues/9600

Can you provide more details about Docker version?

**Comment by arun-gupta** [comment]
@eheb any more updates?

**Comment by arun-gupta** [comment]
@eheb any more updates. This worked for several people at JavaZone yesterday.

**Comment by arun-gupta** [comment]
Related to https://github.com/javaee-samples/docker-java/issues/89.

Closing this issue as pre-packaged tar files can be downloaded.
