### ISSUE TITLE
Kubernetes VAGRANT PROVIDER

### ISSUE THREAD

**Issue by fthamura** [javaee-samples/docker-java#93]
I try in linux the kubernetes setup using the tutorial setup , it asking gcloud.

based on kubernetes.io tutorial it should have VAGRANT_DEFAULT_PROVIDEr which it is missing in the tutorial

export VAGRANT_DEFAULT_PROVIDER=virtualbox

so I add and make a pull

**Comment by arun-gupta** [comment]
Complete instructions to setup Kubernetes are at:

https://htmlpreview.github.io/?https://github.com/javaee-samples/docker-java/blob/master/readme.html#_kubernetes

There is no need to setup `VAGRANT_DEFAULT_PROVIDER`.
